### ISSUE TITLE
Installation issues & HuggingFace model loading problem

### ISSUE THREAD

**Issue by ecekt** [ilkerkesen/pixel-m4#1]
Hi, while creating the environment using the environment.yml, I get the following warnings, and at the end, it says that there are incompatible packages. Conda tries to resolve them, but it takes a very long time and fails in the end.  

```
Collecting package metadata (repodata.json): - WARNING conda.models.version:get_matcher(542): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.9.0.*, but conda is ignoring the .* and treating it as 1.9.0
WARNING conda.models.version:get_matcher(542): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.8.0.*, but conda is ignoring the .* and treating it as 1.8.0
WARNING conda.models.version:get_matcher(542): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.6.0.*, but conda is ignoring the .* and treating it as 1.6.0
WARNING conda.models.version:get_matcher(542): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.7.1.*, but conda is ignoring the .* and treating it as 1.7.1
done
Solving environment: - | 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed
```

I tried the installation on another machine, where I got 'ClobberError: This transaction has incompatible packages due to a shared path.' I believe this is more about my machine, but it seems to install pixel at the end anyway, so I tried the Japanese Dependency Parsing, which throws the following errors: 

```
INFO - pixel.data.rendering.rendering_utils - https://huggingface.co/Team-PIXEL/pixel-m4/resolve/main/text_renderer_config.json not found in cache or force_download set to True
```

```
Can't load text renderer for 'Team-PIXEL/pixel-m4'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'Team-PIXEL/pixel-m4' is the correct path to a directory containing a text_renderer_config.json file
```

I was thinking maybe I should not use the environment.yml and try to install the required libraries in another way manually. Finally, I also tried to download the pretrained model from HuggingFace, simply trying the lines below:

```
from transformers import AutoModelForPreTraining
model = AutoModelForPreTraining.from_pretrained("Team-PIXEL/pixel-m4", torch_dtype="auto")
```

Unfortunately, this also failed, raising an error about CONFIG_MAPPING.

```
/transformers/models/auto/configuration_auto.py", line 643, in __getitem__
    raise KeyError(key)
KeyError: 'pixel'
```

I'd appreciate it if you could give me some pointers!

**Comment by ilkerkesen** [comment]
@ecekt I guess you are trying to import the model using the `AutoModel` classes present in the HuggingFace's `transformers` package, which causes the issue. PIXEL-based models currently are not a part of the HuggingFace, so the `AutoModel` classes do not support them. To overcome the issue, this codebase implements its own `AutoModel` classes. So, the following code snippet should fix this issue,

```python
from pixel import AutoModelForPretraining
# or from pixel import PIXELForPretraining
model = AutoModelForPreTraining.from_pretrained("Team-PIXEL/pixel-m4", torch_dtype="auto")
```

**Comment by ecekt** [comment]
Hi @ilkerkesen, I'm afraid this also doesn't work. I think pixel is not being installed properly. 

`DEPRECATION: Legacy editable install of pixel==0.1.0 from file:myroot/pixel-m4 (setup.py develop) is deprecated. pip 25.1 will enforce this behaviour change. A possible replacement is to add a pyproject.toml or enable --use-pep517, and use setuptools >= 64. If the resulting installation is not behaving as expected, try using --config-settings editable_mode=compat. Please consult the setuptools documentation for more information. Discussion can be found at https://github.com/pypa/pip/issues/11457`

I tried using --config-settings editable_mode=compat, it just appears to install pixel but unable to import anything from it. Even when I cd to the src/pixel directory, AutoModelForPretraining is not being imported.

> from pixel import AutoModelForPretraining
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'AutoModelForPretraining' from 'pixel' (myroot/pixel-m4/src/pixel/__init__.py)

I was able to install pixel using the original PIXEL repo, are there significant differences in terms of the libraries between that repo and this one?

**Comment by ilkerkesen** [comment]
I made a typo in the comment: not Pre**t**raining, it should be Pre**T**raining. The following snippet works on my environment, could you check it?

```python
from pixel import AutoModelForPreTraining
model = AutoModelForPreTraining.from_pretrained("Team-PIXEL/pixel-m4")
```

**Comment by ecekt** [comment]
Thanks, this worked! I'm still unable to verify the installation using the Japanese Dependency Parsing example, though. It's throwing the same errors I reported in my first post. I will work a bit more on it and get back to you later. Thanks!

**Comment by ecekt** [comment]
I think there was a problem with the URL that was being passed when trying to load the renderer in rendering_utils.py. So, instead, I downloaded the whole model folder manually into my HuggingFace cache directory. Then, I set --model_name_or_path to that directory. I managed to move past those errors above, I will update you once I get the results.

```
from huggingface_hub import snapshot_download

local_dir = snapshot_download(repo_id="Team-PIXEL/pixel-m4")
print("Model cached at:", local_dir)
```

**Comment by ecekt** [comment]
Here are the results, do they seem reasonable to you? I see that test_las is exactly the same as the one you reported in the README, although the test loss is different. 

```
***** train metrics *****
  epoch                    =      81.08
  train_loss               =     0.1245
  train_runtime            = 1:11:34.06
  train_samples            =       7050
  train_samples_per_second =    223.564
  train_steps_per_second   =      3.493

***** eval metrics *****
  eval_las                =    92.8298
  eval_loss               =      0.578
  eval_runtime            = 0:00:03.06
  eval_samples            =        507
  eval_samples_per_second =     165.37
  eval_steps_per_second   =     20.875
  eval_uas                =    94.3273

***** test metrics *****
  test_las                =    90.8777
  test_loss               =     0.7478
  test_runtime            = 0:00:03.21
  test_samples            =        543
  test_samples_per_second =    169.106
  test_steps_per_second   =     21.177
  test_uas                =    92.9646
```

**Comment by ilkerkesen** [comment]
It seems reasonable, but I guess I might have chosen the wrong language for the test, since there is relatively smaller difference between the model performances. Maybe you could do the same test in Chinese also as well. One thing we know is that results may vary across different random seeds. Your test loss is also different than the loss produced by my implementation, but I also observed small variations across different HPC systems.

However, if your environment includes the same versions of `cairo`, `pango` packages and other related packages, it should be fine.

**Comment by ilkerkesen** [comment]
I'm closing this issue as I assume it is resolved.
